---
# tasks file for drbd
- name: Create drbdpool volume group
  lvg:
    vg: drbdpool
    pvs: "{{ DRBD_device }}"
  become: true

- name: Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.linbit.com/package-signing-pubkey.asc
  become: true
  when: gpg_check is true

- name: Configure pacemaker
  ansible.builtin.include_tasks: "rhel-{{ ansible_distribution_major_version }}.yml"
  # when: ansible_distribution_major_version == "7"

- name: Install semanage
  ansible.builtin.yum:
    name: policycoreutils-python-utils
    state: present
  become: true

- name: Configure SELinux for DRBD
  command: semanage permissive -a drbd_t
  become: true
