- name: Fail when
  ansible.builtin.fail:
    msg: "Only RHEL is supported"
  when: ansible_distribution != "RedHat"

- name: Fail when
  ansible.builtin.fail:
    msg: "Major Version must be 7, 8 or 9"
  when: ansible_distribution_major_version != "7" and ansible_distribution_major_version != "8" and ansible_distribution_major_version != "9"
