---
- name: Install RDQM
  ansible.builtin.include_tasks: install-rdqm.yml

- name: Configure firewall
  ansible.builtin.include_tasks: firewall.yml

- name: Configure static routes to hadr hosts
  ansible.builtin.include_tasks: static-routes.yml

- name: Set a fixed hostname
  ansible.builtin.command: "hostnamectl --static set-hostname {{ inventory_hostname }}"
  become: true

- name: Configure Pacemaker cluster and DRBD hosts
  ansible.builtin.include_tasks: cluster.yml
