---
# tasks file for rdqm
- name: Create sudoers file for mqm
  copy:
    dest: /etc/sudoers.d/mqm
    content: |
      mqm ALL=(root) NOPASSWD: /opt/mqm/bin/crtmqm, /opt/mqm/bin/dltmqm, /opt/mqm/bin/rdqmadm, /opt/mqm/bin/rdqmstatus, /opt/mqm/bin/rdqmdr
  become: true

- name: Create rdqmadmin account
  user:
    name: rdqmadmin
    group: mqm
    groups: haclient
    password: "{{ rdqmadmin_password }}"
  become: true

- name: Include ssh task
  ansible.builtin.include_tasks: ssh.yml
  when: mqm_user_ssh is true

- name: Include ssh task
  ansible.builtin.include_tasks: ssh-dr.yml
  when: mqm_user_ssh is true

- name: Update rdqm.ini on primary nodes
  ansible.builtin.template:
    src: rdqm.ini.j2
    dest: /var/mqm/rdqm.ini
  vars:
    Name1: "{{ hostvars[groups['rdqm'][0]].inventory_hostname }}"
    Name2: "{{ hostvars[groups['rdqm'][1]].inventory_hostname }}"
    Name3: "{{ hostvars[groups['rdqm'][2]].inventory_hostname }}"
    IP1: "{{ hostvars[groups['rdqm'][0]].rdqm_ha_replication }}"
    IP2: "{{ hostvars[groups['rdqm'][1]].rdqm_ha_replication }}"
    IP3: "{{ hostvars[groups['rdqm'][2]].rdqm_ha_replication }}"
  become: true
  become_user: rdqmadmin
  when: inventory_hostname in groups["rdqm"] and mqm_user_ssh is false

- name: Update rdqm.ini on dr nodes
  ansible.builtin.template:
    src: rdqmdr.ini.j2
    dest: /var/mqm/rdqm.ini
  vars:
    Name1: "{{ hostvars[groups['dr'][0]].inventory_hostname }}"
    Name2: "{{ hostvars[groups['dr'][1]].inventory_hostname }}"
    Name3: "{{ hostvars[groups['dr'][2]].inventory_hostname }}"
    IP1: "{{ hostvars[groups['dr'][0]].rdqm_ha_replication }}"
    IP2: "{{ hostvars[groups['dr'][1]].rdqm_ha_replication }}"
    IP3: "{{ hostvars[groups['dr'][2]].rdqm_ha_replication }}"
  become: true
  become_user: rdqmadmin
  when: inventory_hostname in groups["dr"] and mqm_user_ssh is false
