- name: Create local yum repo for MQ Server
  yum_repository:
    name: "IBM-MQ-{{ mq_release }}-x86_64"
    description: "IBM MQ {{ mq_release }} x86_64"
    baseurl: "file://{{ base_dir }}/mqrdqm/MQServer"
    enabled: true
    gpgcheck: false
  become: true
 
- name: Run mq license script
  command: "{{ base_dir }}/mqrdqm/MQServer/mqlicense.sh -accept"
  become: true

- name: Install MQ Server and Pacemaker
  yum:
    name: MQSeries*
    state: latest
  become: true

- name: Set MQ installation as the primary installation
  command: /opt/mqm/bin/setmqinst -i -p /opt/mqm
  become: true

- name: find rdqm rpm files and register the result 
  find:
    paths: "{{ base_dir }}/mqrdqm/MQServer/Advanced/RDQM"
    patterns: "*.rpm"
  register: rdqm_rpm

- set_fact:
    rdqm_list: "{{ rdqm_rpm.files | map(attribute='path') | list}}"

- name: install rpm files using rpm_list
  yum:
    name: "{{rdqm_list}}"
    state: present
    disable_gpg_check: true
  become: true
