---
- hosts: all
  strategy: free

  tasks:
    - name: Copy MQ Client image
      ansible.builtin.copy:
        src: "{{ mq_client_image }}"
        dest: "{{ mq_client_image }}"
        mode: '0644'
    - name: Create directory for MQ image
      ansible.builtin.file:
        path: "{{ base_dir }}/mqrdqm"
        state: directory
        mode: '0755'
    - name: Unarchive the MQ Client image
      ansible.builtin.unarchive:
        src: "{{ mq_client_image }}"
        dest: "{{ base_dir }}/mqrdqm"
        remote_src: true

    - name: Create local yum repo for MQ Client
      yum_repository:
         name: MQ
         description: "IBM MQ {{ mq_release }} x86_64 Client"
         baseurl: "file://{{ base_dir }}/mqrdqm/MQClient"
         gpgcheck: no
    - name: Install MQ Client
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - MQSeriesClient
          - MQSeriesSamples
          - MQSeriesSDK
    - name: Set MQ installation as the primary installation
      command: /opt/mqm/bin/setmqinst -i -p /opt/mqm

    - name: Create run_rdqmget
      template:
        src: client_env.j2
        dest: /home/mquser/run_rdqmget
        owner: mquser
        group: mquser
        mode: 0755
      vars:
        IP1: "{{ hostvars[groups['rdqm'][0]].ansible_host }}"
        IP2: "{{ hostvars[groups['rdqm'][1]].ansible_host }}"
        IP3: "{{ hostvars[groups['rdqm'][2]].ansible_host }}"
        PORT: 1414
        executable: rdqmget
    - name: Create run_rdqmput
      template:
        src: client_env.j2
        dest: /home/mquser/run_rdqmput
        owner: mquser
        group: mquser
        mode: 0755
      vars:
        IP1: "{{ hostvars[groups['rdqm'][0]].ansible_host }}"
        IP2: "{{ hostvars[groups['rdqm'][1]].ansible_host }}"
        IP3: "{{ hostvars[groups['rdqm'][2]].ansible_host }}"
        PORT: 1414
        executable: rdqmput

