---
- hosts: all
  strategy: free

  tasks:
    - name: Run crtmqm on main primary node
      command: "crtmqm -sx -rr p -rn DRG1 -rp 7001 -fs 3 QMHADR"
      when: inventory_hostname == groups["rdqm"][0]
      become: true
      become_user: rdqmadmin
    
    - name: Run crtmqm on main secondary nodes
      command: "crtmqm -sxs -rr p -rn DRG1 -rp 7001 -fs 3 QMHADR"
      when: inventory_hostname == groups["rdqm"][1] or inventory_hostname == groups["rdqm"][2]
      become: true
      become_user: rdqmadmin
    
    - name: Run crtmqm on dr primary node
      command: "crtmqm -sx -rr s -rn DRG2 -rp 7001 -fs 3 QMHADR"
      when: inventory_hostname == groups["dr"][0]
      become: true
      become_user: rdqmadmin
    
    - name: Run crtmqm on main secondary node
      command: "crtmqm -sxs -rr s -rn DRG2 -rp 7001 -fs 3 QMHADR"
      when: inventory_hostname == groups["dr"][1] or inventory_hostname == groups["dr"][2]
      become: true
      become_user: rdqmadmin
    
    - name: Add Floating Ip to queue manager
      command: "rdqmint -m QMHADR -a -f 10.0.1.20 -l ens35"
      when: inventory_hostname == groups["rdqm"][0] or inventory_hostname == groups["dr"][0]
      become: true
      become_user: rdqmadmin
