---
- hosts: all
  strategy: free
  group_vars:
    - all.yaml
    - drbd.yaml
    - mq.yaml
    - mqm-user.yaml
    - networking.yaml
    - rdqm.yaml
  tasks:
    - ansible.builtin.assert:
        that:
          - groups['rdqm'] | length == 3
          - groups['dr'] | length == 3
    - ansible.builtin.include_role:
        name: os-check
    - name: Copy MQ Server image
      copy:
        src: "{{ mq_server_image }}"
        dest: "{{ mq_server_image }}"
    - name: Create directory for MQ image
      file:
        path: "{{ base_dir }}/mqrdqm"
        state: directory
    - name: Install unzip
      ansible.builtin.yum:
        name: unzip
        state: present
      become: true
    - name: Unarchive the MQ Server image
      unarchive:
        src: "{{ mq_server_image }}"
        dest: "{{ base_dir }}/mqrdqm"
        remote_src: yes
    - ansible.builtin.include_role:
        name: drbd
    - ansible.builtin.include_role:
        name: mq
    - ansible.builtin.include_role:
        name: system-config
    - ansible.builtin.include_role:
        name: ha-config

        