---
- hosts: all
  strategy: free

  tasks:
    - assert:
        that:
          - groups['rdqm'] | length == 3
          - groups['dr'] | length == 3

    - include_role:
        name: os-check

    - name: Copy MQ Server image
      copy:
        src: "{{ mq_server_image }}"
        dest: "{{ mq_server_image }}"

    - name: Create directory for MQ image
      file:
        path: "/home/ibmuser/mqrdqm"
        state: directory

    - name: Unarchive the MQ Server image
      unarchive:
        src: "{{ mq_server_image }}"
        dest: "/home/ibmuser/mqrdqm"
        remote_src: yes

    - name: Create local yum repo for MQ Server
      yum_repository:
        name: "IBM-MQ-{{ mq_release }}-x86_64"
        description: "IBM MQ {{ mq_release }} x86_64"
        baseurl: "file:///home/ibmuser/mqrdqm/MQServer"
        state: present
      become: true

    - include_role:
        name: rdqm-prereqs

    - include_role:
        name: mq-install

    - include_role:
        name: system-config

    - include_role:
        name: ha-config

