- name: Fetch mqm public key
  ansible.builtin.fetch:
    src: "{{ mqm_home }}/.ssh/{{ mqm_ssh_key }}"
    dest: /tmp/rdqm_mqm_keys
  when: inventory_hostname in groups["rdqm"]

- name: Wait for mqm key 1
  ansible.builtin.wait_for:
    path: "/tmp/rdqm_mqm_keys/{{ hostvars[groups['rdqm'][0]].inventory_hostname }}{{ mqm_home }}/.ssh/{{ mqm_ssh_key }}"
  delegate_to: localhost

- name: Wait for mqm key 2
  ansible.builtin.wait_for:
    path: "/tmp/rdqm_mqm_keys/{{ hostvars[groups['rdqm'][1]].inventory_hostname }}{{ mqm_home }}/.ssh/{{ mqm_ssh_key }}"
  delegate_to: localhost

- name: Wait for mqm key 3
  ansible.builtin.wait_for:
    path: "/tmp/rdqm_mqm_keys/{{ hostvars[groups['rdqm'][2]].inventory_hostname }}{{ mqm_home }}/.ssh/{{ mqm_ssh_key }}"
  delegate_to: localhost

- name: Register mqm_1_key
  ansible.builtin.set_fact:
    mqm_1_key: "{{ lookup('file', '/tmp/rdqm_mqm_keys/' + hostvars[groups['rdqm'][0]].inventory_hostname + '{{ mqm_home }}/.ssh/{{ mqm_ssh_key }}') }}"

- name: Register mqm_2_key
  ansible.builtin.set_fact:
    mqm_2_key: "{{ lookup('file', '/tmp/rdqm_mqm_keys/' + hostvars[groups['rdqm'][1]].inventory_hostname + '{{ mqm_home }}/.ssh/{{ mqm_ssh_key }}') }}"

- name: Register mqm_3_key
  ansible.builtin.set_fact:
    mqm_3_key: "{{ lookup('file', '/tmp/rdqm_mqm_keys/' + hostvars[groups['rdqm'][2]].inventory_hostname + '{{ mqm_home }}/.ssh/{{ mqm_ssh_key }}') }}"

- name: Get ssh key for node 1
  ansible.builtin.command: "ssh-keyscan -t {{ ssh_key_type }} {{ hostvars[groups['rdqm'][0]].rdqm_ha_replication }}"
  register: node_1_key

- name: Get ssh key for node 2
  ansible.builtin.command: "ssh-keyscan -t {{ ssh_key_type }} {{ hostvars[groups['rdqm'][1]].rdqm_ha_replication }}"
  register: node_2_key

- name: Get ssh key for node 3
  ansible.builtin.command: "ssh-keyscan -t {{ ssh_key_type }} {{ hostvars[groups['rdqm'][2]].rdqm_ha_replication }}"
  register: node_3_key

- name: Set mqm authorized_keys on node 1
  authorized_key:
    user: mqm
    key: "{{ mqm_2_key }}\n{{ mqm_3_key }}"
    exclusive: true
  when: inventory_hostname == groups['rdqm'][0]

- name: Set mqm authorized_keys on node 2
  authorized_key:
    user: mqm
    key: "{{ mqm_1_key }}\n{{ mqm_3_key }}"
    exclusive: true
  when: inventory_hostname == groups['rdqm'][1]

- name: Set mqm authorized_keys on node 3
  authorized_key:
    user: mqm
    key: "{{ mqm_1_key }}\n{{ mqm_2_key }}"
    exclusive: true
  when: inventory_hostname == groups['rdqm'][2]

- name: Allow mqm to ssh from node 1 to node 2
  ansible.builtin.known_hosts:
    name: "{{ hostvars[groups['rdqm'][1]].rdqm_ha_replication }}"
    key: "{{ node_2_key.stdout }}"
  become: true
  become_user: mqm
  when: inventory_hostname == groups['rdqm'][0]

- name: Allow mqm to ssh from node 1 to node 3
  ansible.builtin.known_hosts:
    name: "{{ hostvars[groups['rdqm'][2]].rdqm_ha_replication }}"
    key: "{{ node_3_key.stdout }}"
  become: true
  become_user: mqm
  when: inventory_hostname == groups['rdqm'][0]

- name: Allow mqm to ssh from node 2 to node 1
  ansible.builtin.known_hosts:
    name: "{{ hostvars[groups['rdqm'][0]].rdqm_ha_replication }}"
    key: "{{ node_1_key.stdout }}"
  become: true
  become_user: mqm
  when: inventory_hostname == groups['rdqm'][1]

- name: Allow mqm to ssh from node 2 to node 3
  ansible.builtin.known_hosts:
    name: "{{ hostvars[groups['rdqm'][2]].rdqm_ha_replication }}"
    key: "{{ node_3_key.stdout }}"
  become: true
  become_user: mqm
  when: inventory_hostname == groups['rdqm'][1]

- name: Allow mqm to ssh from node 3 to node 1
  ansible.builtin.known_hosts:
    name: "{{ hostvars[groups['rdqm'][0]].rdqm_ha_replication }}"
    key: "{{ node_1_key.stdout }}"
  become: true
  become_user: mqm
  when: inventory_hostname == groups['rdqm'][2]

- name: Allow mqm to ssh from node 3 to node 2
  ansible.builtin.known_hosts:
    name: "{{ hostvars[groups['rdqm'][1]].rdqm_ha_replication }}"
    key: "{{ node_2_key.stdout }}"
  become: true
  become_user: mqm
  when: inventory_hostname == groups['rdqm'][2]

- name: Delete password for mqm
  ansible.builtin.command: passwd -d mqm

- name: Lock password for mqm
  ansible.builtin.command: passwd -l mqm
